plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude: ["CNAME", "LICENSE.md", "README.md"]

markdown: kramdown
permalink: pretty

# host: https://www.ultrapop.de
# url: https://www.ultrapop.de

sass:
  style: compressed
  sass_dir: _sass

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      title: ""
      lang: "en"